CREATE DATABASE IF NOT EXISTS APS;

CREATE TABLE USUARIOS (
    ID NUMBER(10),
    NOME VARCHAR(255) NOT NULL,
    SENHA1 VARCHAR(255) NOT NULL,
    SENHA2 VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,

    CONSTRAINT UQ_email UNIQUE (EMAIL),
    CONSTRAINT PK_usuarios PRIMARY KEY (ID)
);